inherit_mode:
  merge:
    - Exclude

inherit_from: common_rubocop.yml

# Configuration parameters: CountComments, ExcludedMethods.
Metrics/BlockLength:
  Exclude:
    - 'lib/radius/spec/rspec.rb'

# Configuration parameters: AllowHeredoc, AllowURI, URISchemes, IgnoreCopDirectives, IgnoredPatterns.
# URISchemes: http, https
Metrics/LineLength:
  Exclude:
    - 'radius-spec.gemspec'
