sudo: false
language: ruby
cache: bundler
bundler_args: --jobs=3 --retry=3 --without documentation debug
script: bin/ci
rvm:
  - 2.5
  - ruby-head
matrix:
  allow_failures:
    - rvm: ruby-head
  fast_finish: true
