language: ruby
cache: bundler
bundler_args: --jobs=3 --retry=3 --without documentation debug
before_script:
  - "bin/ci-code-review"
script: bin/ci
rvm:
  - 2.6
  - 2.5
  - ruby-head
jobs:
  allow_failures:
    - rvm: ruby-head
  fast_finish: true
