---
http_interactions:
- request:
    method: get
    uri: http://example.com/
    body:
      encoding: US-ASCII
      string: ''
    headers:
      Accept-Encoding:
      - gzip;q=1.0,deflate;q=0.6,identity;q=0.3
      Accept:
      - "*/*"
      User-Agent:
      - Ruby
      Authorization:
      - "<AUTHORIZATION_HEADER>"
  response:
    status:
      code: 200
      message: OK
    headers:
      Cache-Control:
      - max-age=604800
      Content-Type:
      - text/html; charset=UTF-8
      Content-Length:
      - '606'
    body:
      encoding: ASCII-8BIT
      string: "Basic Response"
    http_version:
  recorded_at: Tue, 25 Sep 2018 17:06:36 GMT
- request:
    method: get
    uri: http://example.com/
    body:
      encoding: US-ASCII
      string: ''
    headers:
      Accept-Encoding:
      - gzip;q=1.0,deflate;q=0.6,identity;q=0.3
      Accept:
      - "*/*"
      User-Agent:
      - Ruby
      Authorization:
      - "<AUTHORIZATION_HEADER>"
      Content-Type:
      - application/json
  response:
    status:
      code: 200
      message: OK
    headers:
      Cache-Control:
      - max-age=604800
      Content-Type:
      - application/json; charset=UTF-8
      Content-Length:
      - '606'
    body:
      encoding: ASCII-8BIT
      string: "JSON Response"
    http_version:
  recorded_at: Tue, 25 Sep 2018 17:06:36 GMT
recorded_with: VCR 4.0.0
