---
http_interactions:
- request:
    method: get
    uri: "<RADIUS_OAUTH_PROVIDER_URL>/?aws_id=<AWS_ACCESS_KEY_ID>"
    body:
      encoding: US-ASCII
      string: ''
    headers:
      Accept-Encoding:
      - gzip;q=1.0,deflate;q=0.6,identity;q=0.3
      Accept:
      - "*/*"
      User-Agent:
      - Ruby
  response:
    status:
      code: 200
      message: OK
    headers:
      Cache-Control:
      - no-cache
      Content-Type:
      - application/json; charset=utf-8
      Content-Length:
      - '25'
    body:
      encoding: UTF-8
      string: '{"client_id":"<GOOGLE_CLIENT_ID>"}'
    http_version:
  recorded_at: Tue, 25 Sep 2018 15:10:46 GMT
recorded_with: VCR 4.0.0
