---
http_interactions:
- request:
    method: post
    uri: http://www.example.com/search?gid=<GOOGLE_CLIENT_ID_URI>
    body:
      encoding: US-ASCII
      string: secret=<GOOGLE_CLIENT_SECRET_FORM>
    headers:
      Accept-Encoding:
      - gzip;q=1.0,deflate;q=0.6,identity;q=0.3
      Accept:
      - "*/*"
      User-Agent:
      - Ruby
      Content-Type:
      - application/x-www-form-urlencoded
  response:
    status:
      code: 200
      message: OK
    headers:
      Cache-Control:
      - max-age=604800
      Content-Type:
      - text/html; charset=UTF-8
      Content-Length:
      - '345'
    body:
      encoding: UTF-8
      string: "Custom Response"
    http_version:
  recorded_at: Tue, 25 Sep 2018 16:01:34 GMT
recorded_with: VCR 4.0.0
