name: Review Dog
on: [pull_request]
jobs:
  rubocop:
    name: Rubocop
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v1
      - uses: ruby/setup-ruby@v1 # ruby-version pulled .ruby-version file automatically
        with:
          ruby-version: '2.7'
          bundler-cache: true
      - name: rubocop
        uses: reviewdog/action-rubocop@v1
        with:
          github_token: ${{ secrets.github_token }}
          reporter: github-pr-review # Default is github-pr-check
          rubocop_version: gemfile
          rubocop_extensions: rubocop-rails:gemfile

